import type { DemoExperience, DemoWidget } from "./types";

function buildDemoWidget(
  id: number,
  title: string,
  summary: string,
  chartType: DemoWidget["chart_type"],
  data: Record<string, unknown>[],
  config: Record<string, unknown>,
  layout: DemoWidget["layout"],
): DemoWidget {
  return {
    id,
    dashboard_id: 77,
    type: "chart",
    widget_type: "chart",
    source_type: "manual",
    source_id: null,
    execution_type: "snapshot",
    execution_status: "success",
    chart_type: chartType,
    query_sql: null,
    layout,
    title,
    config_json: config,
    data_json: data,
    last_run_at: "2026-05-01T12:00:00+00:00",
    error_message: null,
    insight_index: null,
    has_snapshot: true,
    using_snapshot: true,
    snapshot_created_at: "2026-05-01T12:00:00+00:00",
    source_changed: false,
    created_at: "2026-05-01T12:00:00+00:00",
    source: {
      query: null,
      insight: {
        id: `demo-widget-${id}`,
        type: "distribution",
        title,
        description: summary,
        summary,
        severity: "info",
        metric: null,
        dimension: null,
        value: null,
        confidence: 0.8,
        impact: 0.7,
        priority: "medium",
        sql: null,
        chart_suggestion: chartType === "table" ? "table" : chartType,
        chart_type: chartType ?? "table",
        data,
        columns: data[0] ? Object.keys(data[0]) : [],
        rows: data,
        visualization_suggestion: null,
      },
    },
  };
}

const demoExperience: DemoExperience = {
  dataset: {
    id: 999,
    name: "Wildfire Impact Demo",
    description: "Representative wildfire impact dataset curated for product demos and portfolio walkthroughs.",
    rowCount: 20,
    columnCount: 10,
    sampleQuestions: [
      "Show total superficie_afectada by cobertura",
      "Which provincia has the highest superficie_total?",
      "How does superficie_afectada compare to superficie_total by periodo?",
    ],
    columns: [
      { name: "periodo", type: "date", description: "Observation period for the wildfire event." },
      { name: "provincia", type: "string", description: "Province where the event was registered." },
      { name: "cobertura", type: "string", description: "Coverage segment affected by the wildfire." },
      { name: "superficie_total", type: "number", description: "Total observed surface in hectares." },
      { name: "superficie_afectada", type: "number", description: "Affected surface in hectares." },
    ],
  },
  askAIResult: {
    query_id: 501,
    answer:
      "Bosques leads affected area with 5,945 total hectares, clearly ahead of Pastizales at 2,533 hectares. This suggests the highest absolute impact is concentrated in forest coverage.",
    sql: "SELECT cobertura, SUM(superficie_afectada) AS superficie_afectada_total FROM dataset_999 GROUP BY cobertura ORDER BY superficie_afectada_total DESC",
    rows: [
      { cobertura: "Bosques", superficie_afectada_total: 5945 },
      { cobertura: "Pastizales", superficie_afectada_total: 2533 },
      { cobertura: "Matorrales", superficie_afectada_total: 203 },
      { cobertura: "Turberas", superficie_afectada_total: 110 },
    ],
    columns: ["cobertura", "superficie_afectada_total"],
    chart_suggestion: { type: "bar", x_axis: "cobertura", y_axis: "superficie_afectada_total", explanation: "Grouped categorical comparison" },
    visualization_suggestion: {
      type: "bar",
      x: "cobertura",
      y: "superficie_afectada_total",
      reason: "Detected aggregated categories with a numeric metric.",
    },
    preferred_chart_type: "bar",
    preferred_chart_metric: "superficie_afectada_total",
    preferred_chart_dimension: "cobertura",
    sql_analysis: {
      is_aggregated: true,
      aggregation_functions: ["SUM"],
      group_by_columns: ["cobertura"],
      selected_columns: ["cobertura", "superficie_afectada_total"],
      has_group_by: true,
      has_order_by: true,
      has_limit: false,
    },
    metadata: {
      dataset_id: 999,
      dataset_name: "Wildfire Impact Demo",
      column_count: 10,
      model: "gpt-4.1-mini",
      fallback_used: false,
      cache_hit: false,
    },
  },
  insightNarrative: {
    summary:
      "The dataset shows a clear concentration of wildfire impact in Bosques, which leads total affected area and remains the dominant segment across periods. Surface total and affected surface also move together positively, suggesting larger covered areas tend to accumulate larger absolute impacts.",
    key_findings: [
      "Bosques is the dominant coverage type by total affected surface.",
      "Rio Negro and Cordoba concentrate the highest wildfire-affected surface totals.",
      "superficie_total and superficie_afectada show a strong positive relationship.",
    ],
    risks_or_caveats: [
      "fuente is constant across the dataset and should not be interpreted as an analytical driver.",
      "Latitude and longitude fields are geographic coordinates, not business metrics.",
    ],
    recommended_next_questions: [
      "How does wildfire impact evolve by periodo and provincia?",
      "Which coverage type has the highest affected-to-total surface ratio?",
      "Are there provinces where risk rises faster than affected area?",
    ],
  },
  insights: [
    {
      id: "demo-top-performer",
      type: "top performer",
      title: "Bosques leads total affected surface",
      description: "Bosques accumulates the largest affected surface in the dataset.",
      summary: "Bosques reaches 5,945 affected hectares and clearly dominates the other coverage types.",
      severity: "info",
      metric: "superficie_afectada",
      dimension: "cobertura",
      value: 5945,
      confidence: 0.93,
      impact: 0.88,
      priority: "high",
      sql: "SELECT cobertura, SUM(superficie_afectada) AS total FROM dataset_999 GROUP BY cobertura ORDER BY total DESC",
      chart_suggestion: "bar",
      chart_type: "bar",
      data: [
        { cobertura: "Bosques", total: 5945 },
        { cobertura: "Pastizales", total: 2533 },
        { cobertura: "Matorrales", total: 203 },
        { cobertura: "Turberas", total: 110 },
      ],
      columns: ["cobertura", "total"],
      rows: [],
      visualization_suggestion: { type: "bar", x: "cobertura", y: "total", reason: "Best for comparing grouped totals." },
    },
    {
      id: "demo-correlation",
      type: "correlation",
      title: "Positive relationship between total and affected surface",
      description: "Larger total surfaces tend to correspond with larger affected surfaces.",
      summary: "superficie_total and superficie_afectada move together with a strong positive signal in the sample dataset.",
      severity: "info",
      metric: "superficie_total",
      dimension: "superficie_afectada",
      value: 0.89,
      confidence: 0.9,
      impact: 0.8,
      priority: "high",
      sql: null,
      chart_suggestion: "scatter",
      chart_type: "scatter",
      data: [
        { superficie_total: 1800, superficie_afectada: 540 },
        { superficie_total: 1450, superficie_afectada: 610 },
        { superficie_total: 2100, superficie_afectada: 940 },
        { superficie_total: 1710, superficie_afectada: 790 },
        { superficie_total: 2290, superficie_afectada: 1015 },
        { superficie_total: 2050, superficie_afectada: 710 },
      ],
      columns: ["superficie_total", "superficie_afectada"],
      rows: [],
      visualization_suggestion: {
        type: "scatter",
        x: "superficie_total",
        y: "superficie_afectada",
        reason: "Two numeric axes with enough valid points.",
      },
    },
    {
      id: "demo-distribution",
      type: "distribution",
      title: "Affected surface distribution is right-skewed",
      description: "Most rows cluster in the low-to-mid range, with a smaller number of high-impact records.",
      summary: "The distribution suggests a few large-impact wildfire records drive a disproportionate share of total affected surface.",
      severity: "warning",
      metric: "superficie_afectada",
      dimension: null,
      value: null,
      confidence: 0.84,
      impact: 0.69,
      priority: "medium",
      sql: null,
      chart_suggestion: "bar",
      chart_type: "bar",
      data: [
        { bucket: "0-150", count: 6 },
        { bucket: "151-350", count: 5 },
        { bucket: "351-700", count: 5 },
        { bucket: "701+", count: 4 },
      ],
      columns: ["bucket", "count"],
      rows: [],
      visualization_suggestion: { type: "bar", x: "bucket", y: "count", reason: "Bucketed distribution snapshot." },
    },
  ],
  dashboardNarrative: {
    summary:
      "This demo dashboard summarizes the wildfire impact dataset around concentration of affected area, the strongest coverage drivers, and the relationship between total and affected surface.",
    key_findings: [
      "Bosques remains the highest-impact coverage type.",
      "Affected surface is concentrated in a few large records rather than evenly distributed.",
      "The correlation view suggests the biggest wildfire footprints also drive the largest absolute impact.",
    ],
    risks_or_caveats: ["The demo dataset is intentionally compact and optimized for product storytelling rather than statistical completeness."],
    recommended_next_actions: [
      "Compare wildfire impact by provincia and periodo.",
      "Track relative impact, not only absolute hectares.",
    ],
    stale_or_failed_widgets: [],
  },
  dashboard: {
    id: 77,
    name: "Wildfire Executive Demo",
    dataset_id: 999,
    auto_refresh_enabled: true,
    refresh_interval_minutes: 60,
    last_successful_refresh_at: "2026-05-01T12:00:00+00:00",
    next_refresh_at: "2026-05-01T13:00:00+00:00",
    freshness_status: "fresh",
    created_at: "2026-05-01T12:00:00+00:00",
    updated_at: "2026-05-01T12:00:00+00:00",
    widgets: [
      buildDemoWidget(
        1,
        "Affected surface by coverage",
        "Bosques dominates total affected surface.",
        "bar",
        [
          { cobertura: "Bosques", superficie_afectada_total: 5945 },
          { cobertura: "Pastizales", superficie_afectada_total: 2533 },
          { cobertura: "Matorrales", superficie_afectada_total: 203 },
          { cobertura: "Turberas", superficie_afectada_total: 110 },
        ],
        { type: "bar", x: "cobertura", y: "superficie_afectada_total" },
        { column_span: 2, order: 0, use_snapshot: true, x: 0, y: 0, width: 6, height: 8 },
      ),
      buildDemoWidget(
        2,
        "Surface correlation",
        "Larger total surfaces tend to generate larger affected surfaces.",
        "scatter",
        [
          { superficie_total: 1800, superficie_afectada: 540 },
          { superficie_total: 1450, superficie_afectada: 610 },
          { superficie_total: 2100, superficie_afectada: 940 },
          { superficie_total: 1710, superficie_afectada: 790 },
        ],
        { type: "scatter", x: "superficie_total", y: "superficie_afectada" },
        { column_span: 2, order: 1, use_snapshot: true, x: 6, y: 0, width: 6, height: 8 },
      ),
      buildDemoWidget(
        3,
        "Affected surface distribution",
        "Impact is concentrated in a smaller number of large records.",
        "bar",
        [
          { bucket: "0-150", count: 6 },
          { bucket: "151-350", count: 5 },
          { bucket: "351-700", count: 5 },
          { bucket: "701+", count: 4 },
        ],
        { type: "bar", x: "bucket", y: "count" },
        { column_span: 1, order: 2, use_snapshot: true, x: 0, y: 8, width: 6, height: 8 },
      ),
    ],
  },
};

export function getDemoExperience(): DemoExperience {
  return demoExperience;
}
